FROM stagex/pallet-clang-gnu-busybox AS build
ARG VERSION
ADD fetch/libsodium-${VERSION}.tar.gz .
WORKDIR /libsodium-${VERSION}
RUN --network=none <<-EOF
	set -ex
	./configure --prefix=/usr
	make
	make DESTDIR="/rootfs" install
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
