FROM stagex/bootstrap-stage3 AS build
ARG TARGETARCH
ARG VERSION
COPY --from=stagex/core-busybox . /
COPY --from=stagex/core-libzstd . /
COPY --from=stagex/core-llvm . /
COPY --from=stagex/core-make . /
COPY --from=stagex/core-musl . /
ADD fetch/zlib-${VERSION}.tar.gz .
WORKDIR /zlib-${VERSION}
ENV CFLAGS="-fPIC"
RUN --network=none <<-EOF
	set -eux; \
	./configure \
		--prefix=/usr \
		--libdir=/usr/lib \
		--shared; \
	make -j "$(nproc)"
	make DESTDIR=/rootfs install
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
