FROM scratch as base
ENV VERSION=0.22.4
ENV SRC_HASH=c1e0bb2a4427a9024390c662cd532d664c4b36b8ff444ed5e54b115fdb7a1aea
ENV SRC_FILE=gettext-${VERSION}.tar.gz
ENV SRC_SITE=https://ftp.gnu.org/gnu/gettext/${SRC_FILE}

FROM base as fetch
ADD --checksum=sha256:${SRC_HASH} ${SRC_SITE}

FROM fetch as build
COPY --from=busybox . /
COPY --from=gcc . /
COPY --from=binutils . /
COPY --from=make . /
COPY --from=musl . /
RUN tar -xf ${SRC_FILE}
WORKDIR gettext-${VERSION}
ENV M4=/usr/bin/m4
RUN <<-EOF
	set -eux
	./configure \
		--prefix=/usr
	make
EOF

from build as install
RUN make DESTDIR=/rootfs install
RUN find /rootfs -exec touch -hcd "@0" "{}" +

FROM scratch as package
COPY --from=install /rootfs /
