ARG VERSION=fc6eeb6bd75ea0d0025a79ea9fe45614bd60ba14
ARG SRC_SITE=https://codeload.github.com/lrvick/live-bootstrap/legacy.tar.gz
ARG SRC_HASH=0c268b19cf9f4eefdaf45dab64ac393ccf8ee43de58f0721624cab358044bf78
FROM debian@sha256:bac353db4cc04bc672b14029964e686cd7bad56fe34b51f432c1a1304b9928da as debian

FROM debian as fetch
ARG VERSION
ENV VERSION=${VERSION}
ARG SRC_SITE
ENV SRC_SITE=${SRC_SITE}
ARG SRC_HASH
ENV SRC_HASH=${SRC_HASH}
WORKDIR /home/user
RUN \
	--mount=type=cache,target=/var/cache/apt \
	--mount=type=cache,target=/var/lib/apt \
	apt update && apt install -y curl
RUN <<-EOF
	set -uex
	curl -C - ${SRC_SITE}/${VERSION} -o live-bootstrap.tgz
	echo "${SRC_HASH}  live-bootstrap.tgz" | sha256sum -c
	tar -xvf live-bootstrap.tgz
	mv lrvick-live-bootstrap-* live-bootstrap
	live-bootstrap/download-distfiles.sh
EOF

FROM debian as config
COPY --from=fetch . /
RUN --network=none <<-EOF
	set -eux
	mkdir -p /rootfs/external
	cd /home/user/live-bootstrap
	cp -R distfiles /rootfs/external/
	cp -R steps seed/* /rootfs/
	export CORES=$(nproc --all)
	printf "\
	FORCE_TIMESTAMPS=False\n\
	CHROOT=True\n\
	UPDATE_CHECKSUMS=False\n\
	JOBS=${CORES}\n\
	SWAP_SIZE=0\n\
	FINAL_JOBS=${CORES}\n\
	INTERNAL_CI=False\n\
	INTERACTIVE=False\n\
	BARE_METAL=False\n\
	EXTERNAL_SOURCES=True\n\
	DISK=sda1\n\
	KERNEL_BOOTSTRAP=False\n\
	BUILD_KERNELS=False" \
	> /rootfs/steps/bootstrap.cfg
	touch /rootfs/steps/lwext4-1.0.0-lb1/files/fiwix-file-list.txt
EOF

FROM stagex/stage0 as build
ENV ARCH_DIR=x86
ENV ARCH=x86
COPY --from=config /rootfs .
RUN --network=none \
	["/x86/bin/kaem","--verbose","--strict","--file","./after.kaem"]

FROM build as install
ENV PATH=/bin:/usr/sbin:/usr/bin
RUN --mount=type=cache,target=/rootfs \
	--network=none \
<<-EOF
	set -eux
	rm -rf /usr/lib/python*/__pycache__
	mkdir -p /rootfs/etc /rootfs/home/user /rootfs/tmp
	chown -R 1000:1000 /rootfs/home/user /rootfs/tmp
	cp -R $(ls -d /etc/* | grep -v '\(resolv.conf\|hosts\)') /rootfs/etc/
	cp -R lib usr bin var /rootfs/
	echo "user:x:1000:" > /rootfs/etc/group
	echo "user:x:1000:1000::/home/user:/bin/bash" > /rootfs/etc/passwd
	find /rootfs -exec touch -hcd "@0" "{}" +
EOF

FROM scratch as package
COPY --from=install /rootfs /
USER 1000:1000
ENTRYPOINT ["/bin/bash"]
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV USER=user
ENV HOME=/home/user
ENV TZ=UTC
ENV LANG=C.UTF-8
ENV SOURCE_DATE_EPOCH=1
ENV KCONFIG_NOTIMESTAMP=1
ENV PS1="stage1 $ "
