FROM stagex/pallet-clang-gnu-busybox AS build
ARG VERSION
COPY --from=stagex/pallet-cython . /
COPY --from=stagex/user-gperf . /
ADD fetch/libseccomp-${VERSION}.tar.gz .
WORKDIR /libseccomp-${VERSION}
RUN --network=none <<-EOF
	./configure \
		--prefix=/usr \
		--infodir=/usr/share/info \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--enable-python \
		--enable-static
	make
	make DESTDIR=/rootfs install
	find /rootfs | grep -E "(/__pycache__$|\.pyc$|\.pyo$|install_files.txt)" | xargs rm -rf
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
