name: StageX Package-Updates

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  test-run:
    runs-on: lugges-micro
    container:
      image: codeberg.org/stagex/release-bot:1.0.2@sha256:61c05bc8b97ea5e555f5ff7986bff32a81a81373b97a2e1e168e97db15df7ac6
    steps:
      - name: Create PR
        run: /app/venv/bin/python3 /app/main.py upgrade
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
