name: merge-main-check
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

defaults:
  run:
    shell: 'sh -e {0}'

jobs:
  check:
    name: Check if non-staging -> main
    runs-on: shell
    if: github.base_ref == 'main' && !startsWith(github.ref, 'refs/heads/release/') && github.head_ref != 'staging'
    steps:
      - name: Check if non-staging -> main
        run: echo 'Cannot merge non-staging branch to main'; exit 1
