name: merge-main-check
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

defaults:
  run:
    shell: 'sh -e {0}'

jobs:
  check:
    runs-on: shell
    if: github.base_ref == 'main'
    steps:
      - name: Check if non-staging -> main
        if: github.head_ref != 'staging'
        run: echo 'Cannot merge non-staging branch to main'; exit 1

      - name: Check if staging -> main
        if: github.head_ref == 'staging'
        run: echo 'Merge from staging branch to main allowed'; exit 0

