FROM stagex/pallet-gcc-gnu-busybox AS build
ARG VERSION
COPY --from=stagex/core-ncurses . /
COPY --from=stagex/user-libassuan . /
COPY --from=stagex/user-libgpg-error . /
COPY --from=stagex/user-libgpg-error . /
ADD fetch/pinentry-${VERSION}.tar.bz2 .
WORKDIR /pinentry-${VERSION}
RUN --network=none <<-EOF
	set -eux
	./configure \
		--prefix=/usr \
		--disable-pinentry-gtk2 \
		--disable-pinentry-gnome3 \
		--disable-pinentry-qt \
		--enable-fallback-curses \
		--disable-libsecret \
		--enable-pinentry-curses \
		--enable-pinentry-tty
	make
	make DESTDIR="/rootfs" install
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
