FROM scratch AS build
ARG VERSION
COPY --from=stagex/core-busybox . /
COPY --from=stagex/core-musl . /
COPY --from=stagex/core-make . /
COPY --from=stagex/core-zlib . /
COPY --from=stagex/core-llvm . /
COPY --from=stagex/core-mold . /
COPY --from=stagex/core-onetbb . /
COPY --from=stagex/core-libzstd . /
ADD fetch/gawk-${VERSION}.tar.xz .
WORKDIR /gawk-${VERSION}
RUN --network=none <<-EOF
	set -ex
	./configure \
		--prefix=/usr \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--disable-nls \
		--disable-pma
	make -j "$(nproc)"
EOF
RUN --network=none make DESTDIR="/rootfs" install
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
