FROM stagex/pallet-clang-gnu-busybox AS build
ARG VERSION
COPY --from=stagex/core-openssl . /
COPY --from=stagex/user-util-linux . /
COPY --from=stagex/user-e2fsprogs . /
COPY --from=stagex/user-openldap . /
COPY --from=stagex/user-groff . /
COPY --from=stagex/user-libevent . /
COPY --from=stagex/user-libverto . /
ADD fetch/krb5-${VERSION}.tar.gz .
WORKDIR /krb5-${VERSION}/src
RUN --network=none <<-EOF
	./configure \
		CPPFLAGS="-fPIC -I/usr/include/et" \
		WARN_CFLAGS= \
		--prefix=/usr \
		--localstatedir=/var/lib \
		--enable-shared \
		--disable-nls \
		--disable-static \
		--disable-rpath \
		--with-system-et \
		--with-system-ss \
		--with-system-verto \
		--without-tcl \
		--with-ldap
	make
	make DESTDIR=/rootfs install
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
