FROM stagex/pallet-clang-cmake-busybox AS build
COPY --from=stagex/user-swig . /
ARG VERSION
ADD fetch/lldb-${VERSION}.tar.xz .
ADD fetch/cmake-${VERSION}.tar.xz .
WORKDIR /lldb-${VERSION}.src
RUN <<-EOF
	mv ../cmake-${VERSION}.src ../cmake
	cmake \
		-B build \
		-G Ninja \
		-Wno-dev \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_SKIP_RPATH=ON \
		-DLLD_BUILT_STANDALONE=ON \
		-DLLVM_INCLUDE_TESTS=OFF \
		-DLLVM_LINK_LLVM_DYLIB=ON \
		-DCMAKE_POSITION_INDEPENDENT_CODE=ON
	cmake --build build --target all
	DESTDIR="/rootfs" cmake --install build
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
