FROM stagex/pallet-go AS build
ARG VERSION
ADD fetch/mockgen-${VERSION}.tar.gz .
ENV GOPATH=/cache/go
ENV GOCACHE=/cache/
ENV GOWORK=off
ENV GOPROXY=https://proxy.golang.org,direct
ENV GOSUMDB=sum.golang.org
ENV CGO_ENABLED=0
ENV GOHOSTOS=linux
ENV GOHOSTARCH=amd64
ENV GOFLAGS=-trimpath
WORKDIR /mock-${VERSION}
RUN mkdir -p ${GOPATH}
RUN go get ./...
RUN --network=none <<-EOF
	go build -o bin/mockgen ./mockgen
	mkdir -p /rootfs/usr/bin/
	cp bin/mockgen /rootfs/usr/bin/
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
