FROM stagex/pallet-clang-meson-busybox AS build
ARG VERSION
COPY --from=stagex/user-glib . /
COPY --from=stagex/core-pcre2 . /
ADD fetch/libslirp-${VERSION}.tar.gz .
#HACK: Will need to create an optional var for the commot
WORKDIR /libslirp-v${VERSION}-ce314e39458223c2c42245fe536fbe1bcd94e9b1
RUN --network=none <<-EOF
  meson setup \
		--default-library=shared \
		--prefix=/usr \
		. output
	meson compile -C output
	meson install --no-rebuild -C output
	DESTDIR=/rootfs meson install --no-rebuild -C output
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
