FROM stagex/busybox as base
WORKDIR ${HOME}
ENV SRC_SITE http://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/
ENV SRC_VERSION 6.6
ENV SRC_HASH d926a06c63dd8ac7df3f86ee1ffc2ce2a3b81a2d168484e76b5b389aba8e56d0

FROM base as fetch
RUN wget ${SRC_SITE}/linux-${SRC_VERSION}.tar.xz
RUN echo "${SRC_HASH}  linux-${SRC_VERSION}.tar.xz" | sha256sum -c

FROM fetch as build
RUN tar -xf linux-${SRC_VERSION}.tar.xz
WORKDIR linux-${SRC_VERSION}
COPY --from=stagex/gcc . /
COPY --from=stagex/binutils . /
COPY --from=stagex/musl . /
RUN gcc usr/gen_init_cpio.c -o usr/gen_init_cpio

FROM build as install
USER 0:0
RUN set -eux; \
    mkdir -p /rootfs/usr/bin; \
    cp -a usr/gen_initramfs.sh /rootfs/usr/bin/gen_initramfs; \
    cp -a usr/gen_init_cpio /rootfs/usr/bin; \
    find /rootfs -exec touch -hcd "@0" "{}" +

FROM scratch as package
COPY --from=install /rootfs /
