FROM stagex/pallet-clang-gnu-busybox AS build
ARG VERSION
COPY --from=stagex/user-skalibs . /
ADD fetch/utmps-${VERSION}.tar.gz .
WORKDIR /utmps-${VERSION}
RUN --network=none <<-EOF
	./configure \
		--enable-shared \
		--enable-static \
		--prefix=/usr \
		--disable-allstatic \
		--libdir=/usr/lib \
		--libexecdir=/lib/utmps \
		--with-lib=/usr/lib \
		--with-dynlib=/lib
    make
		make DESTDIR=/rootfs install
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
