# Allow all interfaces
interface eth0
interface eth1
interface ens*
interface enp*
interface enx*
interface wlan0

# Basic DHCP options
option subnet_mask, router, domain_name_servers
timeout 10
retry 30
