# Zero-based indexing is sure great in programming languages,
# but not so much in terminal multiplexers where that zero is
# all the way on the other side of the keyboard.
set-option -g base-index 1

set-option -g status on
set-option -g status-interval 1

# We should not have more than one session, but it's still possible.
# Therefore...
set-option -g status-left "[#S] "

# Just so we can use `-ag` properly later
set-option -g status-right ""

# The current power battery level
set-option -ag status-right '#(test -d /sys/class/power_supply/BAT0 && printf " [%%s%%%%]" "$(cat /sys/class/power_supply/BAT0/capacity)")'

# Current date and time, in case it's relevant, and has drifted
set-option -ag status-right " [%Y-%m-%d %H:%M:%S]"

# because cyan on black is cool, and pops out
set-option -g status-style "bg=color0 fg=color6"
set-option -g status-position bottom

# we don't have much screen space, let's limit what's displayed
set-window-option -g window-status-bell-style "bold"
set-window-option -g window-status-current-format "#I:#W"
set-window-option -g window-status-format "#I:#W"

# our "focused" window and pane is the brighter one
set-window-option -g window-status-style "fg=color6"
set-window-option -g window-status-current-style "fg=color14"
set-option -g pane-border-style "fg=color6"
set-option -g pane-active-border-style "fg=color14"
set-option -g message-style "fg=color6 bg=color0"
