FROM scratch AS build 
COPY --from=stagex/busybox . /
COPY --from=stagex/musl . /
COPY --from=stagex/openssl . /
COPY --from=stagex/python:3.12.0 . /
COPY --from=stagex/zlib . /

RUN python -m ensurepip --upgrade
RUN python -m pip install --upgrade pip

WORKDIR /app

COPY requirements.txt . 
RUN python -m pip install --no-cache-dir --upgrade -r ./requirements.txt
COPY . . 

ENTRYPOINT ["/usr/bin/python"]
CMD ["main.py"]
