FROM stagex/pallet-clang-gnu-busybox AS build
ARG VERSION
COPY --from=stagex/user-pcsc-lite . /
COPY --from=stagex/user-libusb . /
ADD fetch/ccid-${VERSION}.tar.bz2 .
WORKDIR /ccid-${VERSION}
RUN --network=none <<-EOF
	./configure \
		--prefix=/usr \
		--sysconfdir=/etc \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--localstatedir=/var \
		--enable-twinserial
	make
	make DESTDIR=/rootfs install
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
