[agent]
# Configuration format: https://github.com/keylime/rust-keylime/blob/v0.2.10/keylime-agent.conf
# All options can be overridden via KEYLIME_AGENT_<OPTION> environment variables

version = "2.4"
uuid = "stagex-enclave"
run_as = ""
skip_registration = true
ip = "0.0.0.0"
port = 9002
contact_ip = "0.0.0.0"
contact_port = 9002
registrar_ip = "127.0.0.1"
registrar_port = 8890
registrar_tls_port = 8891
registrar_tls_enabled = false
registrar_tls_ca_cert = "default"
enable_agent_mtls = false
keylime_dir = "/run/keylime"
server_key = "default"
server_key_password = ""
payload_key = "default"
payload_key_password = ""
server_cert = "default"
trusted_client_ca = "default"
enc_keyname = "derived_tci_key"
dec_payload_file = "decrypted_payload"
secure_size = "1m"
extract_payload_zip = true
enable_revocation_notifications = false
revocation_actions_dir = "/usr/libexec/keylime"
revocation_notification_ip = "127.0.0.1"
revocation_notification_port = 8992
revocation_cert = "default"
revocation_actions = ""
payload_script = ""
enable_insecure_payload = true
allow_payload_revocation_actions = true

# TPM settings
tpm_hash_alg = "sha256"
tpm_encryption_alg = "rsa"
tpm_signing_alg = "rsassa"
ek_handle = "generate"
enable_iak_idevid = false
iak_idevid_template = "detect"
iak_idevid_asymmetric_alg = "rsa"
tpm_ownerpassword = ""
ima_ml_path = "default"
measuredboot_ml_path = "default"
allow_none_tls_verify = false
allow_insecure_devicetpm = false
