[cloud_agent]
uuid = stagex-enclave
tpm_manufacturer = AMZN
tpm_version = 2.0
transport = http
key_permitted = true
verify_plaintext = false
keyfile_encryption_type = asymmetric
rsa_key_size = 2048
allow_none_tls_verify = false
revocation_action = noop
revocation_action_timeout = 0
keylime_ip = 0.0.0.0
keylime_port = 8891
ca_dir = /var/lib/keylime
ssl_dir = /var/lib/keylime/ssl
cert_dir = /var/lib/keylime/certs
agent_uuid_file = /var/lib/keylime/uuid
bootlog_directory = /var/log
allow_insecure_devicetpm = false
tpm = device
tpm_device = /dev/tpmrm0

[storage]
dir = /var/lib/keylime
