[general]
cloud_agent_addr = 0.0.0.0
cloud_agent_port = 8891
verify_agent_addr = 0.0.0.0
verify_agent_port = 8891

[limits]
max_attempts = 10
max_runtime = 600

[tcb]
tcb_event_log_hash_algorithm = sha256

[log]
log_level = INFO
log_file = /var/log/keylime/keylime-agent.log
