FROM scratch AS base 
COPY --from=stagex/busybox . /
COPY --from=stagex/musl . /
COPY --from=stagex/openssl . /
COPY --from=stagex/python . /
COPY --from=stagex/zlib . /
RUN python -m ensurepip --upgrade
RUN python -m pip install --upgrade pip

FROM base AS fetch 
RUN python -m pip install poetry 
WORKDIR /tmp
COPY ./pyproject.toml ./poetry.lock* . 
RUN python -m poetry export -f requirements.txt --output requirements.txt

FROM base AS build
WORKDIR /app
COPY --from=fetch /tmp/requirements.txt .
RUN python -m pip install --no-cache-dir --upgrade -r ./requirements.txt
COPY src/ .

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80"]
