FROM scratch as base
ENV VERSION=3.8.2
ENV SRC_HASH=06c9e13bdf7eb24d4ceb6b59205a4f67c2c7e7213119644430fe82fbd14a0abb
ENV SRC_FILE=bison-${VERSION}.tar.gz
ENV SRC_SITE=https://ftp.gnu.org/gnu/bison/${SRC_FILE}

FROM base as fetch
ADD --checksum=sha256:${SRC_HASH} ${SRC_SITE}

FROM fetch as build
COPY --from=musl . /
COPY --from=busybox . /
COPY --from=gcc . /
COPY --from=binutils . /
COPY --from=make . /
RUN tar -xf ${SRC_FILE}
WORKDIR bison-${VERSION}
RUN --network=none <<-EOF
	set -eux
	M4=/usr/bin/m4 \
	./configure \
		--prefix=/usr
	make
EOF

from build as install
RUN --network=none make DESTDIR=/rootfs install

FROM scratch as package
COPY --from=install /rootfs /
