FROM stagex/pallet-clang-gnu-busybox AS build
ARG VERSION
ADD fetch/strace-${VERSION}.tar.xz .
WORKDIR /strace-${VERSION}
RUN --network=none <<-EOF
	./configure \
		--prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --enable-mpers=no
	make
	make DESTDIR="/rootfs" install
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
