FROM scratch as base
ENV VERSION=1.5.0
ENV SRC_FILE=${VERSION}.tar.gz
ENV SRC_SITE=https://github.com/argp-standalone/argp-standalone/archive/refs/tags/${SRC_FILE}
ENV SRC_HASH=c29eae929dfebd575c38174f2c8c315766092cec99a8f987569d0cad3c6d64f6

FROM base as fetch
ADD --checksum=sha256:${SRC_HASH} ${SRC_SITE} .

FROM fetch as build
COPY --from=busybox . /
COPY --from=gcc . /
COPY --from=binutils . /
COPY --from=make . /
COPY --from=musl . /
COPY --from=autoconf . /
COPY --from=automake . /
COPY --from=m4 . /
RUN tar -xf ${SRC_FILE}
WORKDIR argp-standalone-${VERSION}
RUN ls -lah
RUN <<-EOF
	set -eux
	autoreconf -vif
	CFLAGS="-fPIC" \
	./configure \
		--prefix=/usr \
		--sysconfdir=/etc \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--localstatedir=/var
	make
EOF

FROM build as install
USER 0:0
RUN <<-EOF
	set -eux
	install -D -m644 argp.h /rootfs/usr/include/argp.h
	install -D -m755 libargp.a /rootfs/usr/lib/libargp.a
EOF

FROM scratch as package
COPY --from=install /rootfs /
