FROM alpine@sha256:51b67269f354137895d43f3b3d810bfacd3945438e94dc5ac55fdac340352f48 as apline
FROM debian@sha256:bac353db4cc04bc672b14029964e686cd7bad56fe34b51f432c1a1304b9928da as debian
FROM archlinux@sha256:1f83ba0580a15cd6ad1d02d62ad432ddc940f53f07d0e39c8982d6c9c74e53e0 as arch

FROM scratch as base
ENV VERSION=1.6.0
ENV SRC_SITE=https://github.com/oriansj/stage0-posix/releases/download
ENV SRC_HASH=9260ff69278366e5c056af7b8c436b74773eaa1330a0c6a6b8ab1b5f92e5065c
COPY <<-EOF build.sh
	#!/bin/sh
	set -eux
	wget ${SRC_SITE}/Release_${VERSION}/stage0-posix-${VERSION}.tar.gz
	echo "${SRC_HASH}  stage0-posix-${VERSION}.tar.gz" | sha256sum -c
	tar -xf stage0-posix-${VERSION}.tar.gz
	cd stage0-posix-${VERSION}
	bootstrap-seeds/POSIX/x86/kaem-optional-seed
	mkdir -p /rootfs && cp -R * /rootfs/
	cd /rootfs
	sha256sum x86/bin/* > hashes.txt; \
	find . -exec touch -hcd "@0" "{}" +
EOF

FROM base as build1
COPY --from=debian . /
RUN --mount=type=cache,target=/var/cache/apt <<-EOF
	set -eux
	apt update
	apt install -y wget gcc
	sh build.sh
EOF

FROM base as build2
COPY --from=arch . /
RUN --mount=type=cache,target=/var/cache/pacman/pkg <<-EOF
	set -eux
	pacman -Sy --noconfirm wget gcc
	sh build.sh
EOF

FROM base as build3
COPY --from=alpine . /
RUN --mount=type=cache,target=/var/cache/apk <<-EOF
	set -eux
	apk add wget gcc
	sh build.sh
EOF

FROM scratch as compare
COPY --from=build1 /rootfs/ /a
COPY --from=build2 /rootfs/ /b
COPY --from=build3 /rootfs/ /c

FROM compare as test1
WORKDIR /a
RUN --network=none ["x86/bin/sha256sum","-c","/a/hashes.txt"]
RUN --network=none ["x86/bin/sha256sum","-c","/b/hashes.txt"]
RUN --network=none ["x86/bin/sha256sum","-c","/c/hashes.txt"]

FROM compare as test2
WORKDIR /b
RUN --network=none ["x86/bin/sha256sum","-c","/a/hashes.txt"]
RUN --network=none ["x86/bin/sha256sum","-c","/b/hashes.txt"]
RUN --network=none ["x86/bin/sha256sum","-c","/c/hashes.txt"]

FROM compare as test3
WORKDIR /c
RUN --network=none ["x86/bin/sha256sum","-c","/a/hashes.txt"]
RUN --network=none ["x86/bin/sha256sum","-c","/b/hashes.txt"]
RUN --network=none ["x86/bin/sha256sum","-c","/c/hashes.txt"]

FROM scratch as install
COPY --from=test1 /a/hashes.txt /
COPY --from=test2 /b/hashes.txt /
COPY --from=test3 /c/hashes.txt /
COPY --from=build1 /rootfs /

FROM scratch as package
COPY --from=install / /
CMD ["x86/bin/kaem","--version"]
