FROM stagex/pallet-clang-gnu-busybox AS build
COPY --from=stagex/user-util-macros . /
COPY --from=stagex/user-xorgproto . /
COPY --from=stagex/user-libx11 . /
COPY --from=stagex/user-libxcb . /
COPY --from=stagex/user-libxfixes . /
COPY --from=stagex/user-libxdmcp . /
COPY --from=stagex/user-libxau . /
ARG VERSION
ADD fetch/libXdamage-${VERSION}.tar.xz .
WORKDIR /libXdamage-${VERSION}
ENV SOURCE_DATE_EPOCH=1
RUN --network=none <<-EOF
	./configure \
		--prefix=/usr \
		--sysconfdir=/etc \
		--disable-static
	make
	make install DESTDIR=/rootfs
EOF

FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
