FROM stagex/pallet-clang-gnu-busybox AS build
ARG VERSION
ADD fetch/cpio-${VERSION}.tar.gz .
WORKDIR /cpio-${VERSION}
RUN --network=none <<-EOF
	./configure \
		--prefix=/usr \
		--bindir=/usr/bin \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		gl_cv_func_getcwd_path_max="no, but it is partly working"
	make
	make DESTDIR=/rootfs install
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
