FROM stagex/pallet-clang-cmake-busybox AS build
ARG VERSION
ADD fetch/capnproto-c++-${VERSION}.tar.gz .
WORKDIR /capnproto-c++-${VERSION}
RUN <<-EOF
	cmake \
		-B build \
		-G Ninja \
		-Wno-dev \
		-DCMAKE_INSTALL_PREFIX=/usr/ \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_SHARED_LIBS=True \
		-DMAKE_BUILD_TYPE=None
	cmake --build build
	DESTDIR="/rootfs" cmake --install build
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
