FROM stagex/pallet-clang-gnu-busybox AS build
COPY --from=stagex/core-bash . /
COPY --from=stagex/core-curl . /
COPY --from=stagex/core-openssl . /
COPY --from=stagex/user-json-c . /
COPY --from=stagex/user-libarchive . /
COPY --from=stagex/core-bzip2 . /

ARG VERSION
ADD fetch/elfutils-${VERSION}.tar.bz2 .
WORKDIR /elfutils-${VERSION}
ENV CFLAGS="-D_GNU_SOURCE -Wno-unaligned-access"
ENV LDFLAGS="-Wl,-z,stack-size=2097152"
ADD patches/musl-macros.patch .
WORKDIR /elfutils-${VERSION}
RUN --network=none <<-EOF
	patch -p1 < musl-macros.patch
	autoreconf -vif
	mkdir build
	cd build
	../configure \
		--prefix=/usr \
		--sysconfdir=/etc \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--localstatedir=/var \
		--disable-werror \
		--disable-nls \
		--enable-debuginfod \
		--enable-deterministic-archives \
		--enable-libdebuginfod \
		--with-zstd \
		--program-prefix=eu-
	make
	make DESTDIR=/rootfs install
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
