FROM stagex/busybox as base
ENV SRC_SITE=https://www.zlib.net/
ENV SRC_VERSION=1.3.1
ENV SRC_HASH=9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23
COPY --from=stagex/gcc . /
COPY --from=stagex/binutils . /
COPY --from=stagex/make . /
COPY --from=stagex/musl . /

FROM base as fetch
RUN wget ${SRC_SITE}/zlib-${SRC_VERSION}.tar.gz
RUN echo "${SRC_HASH}  zlib-${SRC_VERSION}.tar.gz" | sha256sum -c

FROM fetch as build
RUN tar -xf zlib-${SRC_VERSION}.tar.gz
WORKDIR zlib-${SRC_VERSION}
RUN set -eux; \
    ./configure \
        --prefix=/usr \
        --libdir=/lib \
        --shared; \
    make

FROM build as install
USER 0:0
RUN set -eux; \
    make DESTDIR=/rootfs install; \
    find /rootfs -exec touch -hcd "@0" "{}" +

FROM scratch as package
COPY --from=install /rootfs /
