FROM stagex/bootstrap-stage3 AS build
ARG TARGETARCH
ARG VERSION
ADD fetch/make-${VERSION}.tar.gz .
WORKDIR /make-${VERSION}
RUN --network=none <<-EOF
	./configure \
		--prefix=/usr \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--disable-nls
	make -j "$(nproc)"
	make DESTDIR="/rootfs" install
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
