FROM stagex/pallet-clang-gnu-busybox AS build
ARG VERSION
COPY --from=stagex/user-npth . /
COPY --from=stagex/user-libgpg-error . /
ADD fetch/libtasn1-${VERSION}.tar.gz .
WORKDIR /libtasn1-${VERSION}
RUN --network=none <<-EOF
	./configure \
		--prefix=/usr/ \
		--bindir=/usr/bin \
    --sysconfdir=/etc \
    --localstatedir=/var \
		--mandir=/usr/share/man \
    --disable-static
	make
	make DESTDIR=/rootfs install
EOF
FROM stagex/core-filesystem AS package
COPY --from=build /rootfs/ /
